<a href="https://colab.research.google.com/github/Gauravkumarlokhande/Gauravkumarlokhande/blob/main/Random_Forest_Regression_sample_input_and_deployment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Random Forest Regressor**

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel('/content/drive/MyDrive/st data.xlsx')

In [3]:
data.drop(columns=['Year'],inplace=True)

In [22]:
def randomf(data):
  dept=str(input('Please enter the name of your dependent variable (same as given in the data): '))
  y=data[dept]
  x=data.drop(columns=[dept])
  test=float(input('please select the size for testing (should be a decimal between 0 and 1): '))
  state=int(input('please specify the random state: '))
  import random
  random.seed(10)
  from sklearn.model_selection import train_test_split as tst
  x_train,x_test,y_train,y_test=tst(x,y,random_state=state,test_size=test)
  print('----------------------------------------------------------------------------------------------')
  print('shape of x_train= {}'.format(x_train.shape))
  print('shape of x_test= {}'.format(x_test.shape))
  print('shape of y_train= {}'.format(y_train.shape))
  print('shape of y_test= {}'.format(y_test.shape))
  print('----------------------------------------------------------------------------------------------')
  
  choice=str(input('Do you want to scale the data (yes or no): '))
  if choice=='yes':
    from sklearn.preprocessing import StandardScaler as STD
    st=STD()
    x_train=st.fit_transform(x_train)
    x_test=st.fit_transform(x_test)
  else:
    print('You have choosen not to scale the data')
  print('-----------------------------------------------------------------------------------------------')
  from sklearn.ensemble import RandomForestRegressor as RFR
  rf=RFR()
  rf.fit(x_train,y_train)
  print('------------------------------------------------------------------------------------------------')
  print('Accuracy score for training data: ', rf.score(x_train,y_train))
  print('Accuracy score for testing data: ',rf.score(x_test,y_test))
  
  y_pred_train=rf.predict(x_train)
  y_pred_test=rf.predict(x_test)
  
  from sklearn.metrics import mean_squared_error
  mse=mean_squared_error(y_test,y_pred_test)
  rmse=np.sqrt(mse)
  
  print('Mean squared error= ',mse)
  print('Root Mean squared error= ',rmse)
  
  from sklearn.metrics import r2_score
  r2=r2_score(y_test,y_pred_test)
  print('R-Squared value= ',r2)
  
  a=x_test.shape
  adjust=1-((1-r2)*(a[0]-1)/(a[0]-1-a[1]))
  print('Adjusted-R Square= ',adjust)
  
  #Deployment
  choose=str(input('Do you wnat to deploy the model? '))
  if choose=='no':
    print('no deployment')
  else:
    def deploy(test_data):
      prediction=rf.predict(test_data)
      df=pd.DataFrame(prediction)
      test_data['Margin(in lakhs)']=prediction  
      test_data
      file_name=str(input('enter the filename you want to save with: '))
      test_data.to_excel('{}.xlsx'.format(file_name))
    test_data_path=input('enter testing data path: ')
    test_data=pd.read_excel('{}'.format(test_data_path),sheet_name='Deploy')
    deploy(test_data)

data_path=input('enter testing data path: ')
data=pd.read_excel('{}'.format(data_path),sheet_name='Sheet1')
data.drop(columns=['Year'],inplace=True)

randomf(data)

enter testing data path: /content/drive/MyDrive/st data.xlsx
Please enter the name of your dependent variable (same as given in the data): Margin(in lakhs)
please select the size for testing (should be a decimal between 0 and 1): 0.3
please specify the random state: 1001
----------------------------------------------------------------------------------------------
shape of x_train= (50, 12)
shape of x_test= (22, 12)
shape of y_train= (50,)
shape of y_test= (22,)
----------------------------------------------------------------------------------------------
Do you want to scale the data (yes or no): no
You have choosen not to scale the data
-----------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Accuracy score for training data:  0.9614125179498298
Accuracy score for testing data:  0.6767202591799844
Mean squared error=  85.27638209056248
Root Mean squared error=  9.234521216097914
R-Squared value=  0.6767202591799844
Adjusted-R Square=  0.2456806047532969
Do you wnat to deploy the model? yes
enter testing data path: /content/drive/MyDrive/st data.xlsx
enter the filename you want to save with: new deployed data

In [18]:
test_data_path=input('enter testing data path: ')
test_data=pd.read_excel('{}'.format(test_data_path),sheet_name='Deploy')
prediction=rf.predict(test_data)
prediction
df=pd.DataFrame(prediction)
test_data['Margin(in lakhs)']=prediction  
test_data

enter testing data path: /content/drive/MyDrive/st data.xlsx

,"Rate Of Breakdown(per 10,000km)",% Load Factor,Traffic Reciept(in lakhs),Rate Of Accident(per lakh kms),Effective Kms(in lakhs),Average No. Of Shedules,KPTL(Diesel),KPL(engine oil),"EPKM(per 10,000km)",Bus Staff Ratio,Crew Duty(in kms),Average Total Offroad,Margin(in lakhs)
0,0.126449,66.678615,173.995385,0.133745,6.820769,64.882308,48.941774,1977.666144,24.739363,6.016154,241.850873,3352.64,-33.742408
1,0.167128,62.508796,170.165385,0.169360,7.081538,66.564615,48.400749,2090.776677,23.067495,5.782631,246.361087,3362.70,-43.465477
2,0.145423,67.127947,178.577692,0.082347,6.885385,65.300000,48.702600,1854.530255,24.739363,5.883407,245.713604,3348.25,-36.612538
3,0.152860,60.789148,166.142308,0.288725,6.961538,64.903846,48.818877,1853.957827,22.495986,5.920315,241.499537,3347.82,-45.032623
4,0.208831,62.457888,178.754615,0.135019,6.931538,64.398462,48.616832,1903.482735,24.357933,5.955422,239.307414,3355.67,-36.645085
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.201538,59.900769,235.780769,0.143846,8.043846,70.993077,46.788450,1814.254635,28.371538,5.813846,211.930769,3481.73,-72.505885
62,0.244615,56.389231,204.903846,0.128462,7.378462,68.488462,46.823569,1513.894922,26.744615,5.908462,206.200000,3456.85,-83.529062
63,0.269231,54.428462,200.860769,0.244615,7.436154,66.237692,46.036486,1686.611875,25.900000,5.858462,204.976923,3471.50,-88.150800
64,0.316154,57.738462,206.119231,0.192308,7.196923,63.827692,45.897021,1895.363702,27.466154,5.850000,201.192308,3491.12,-77.026454
65,0.267692,55.077692,194.008462,0.146154,7.098462,63.931538,45.830605,1778.345508,26.220000,5.820769,206.015385,3482.71,-84.159723